### ISSUE TITLE
Label required for 'Combo box' example

### ISSUE THREAD

**Issue by LukeCGardner** [AdamMather/webaccess#1]
Adding a label to the combo box means AT, such as screen readers or speech recognition programs, can interpret the labels and allows their users to access the content they are attributed to

`<label for="bird-selector">Choose your favourite Bird:</label>
    <select size="1" id="bird-selector" aria-controls="bird-info">
        <option>Black Redstart</option>
        <option>Greenshank</option>
        <option>Meadow Pipit</option>
        <option>Sandwich Tern</option>
    </select>`

**Comment by AdamMather** [comment]
correct markup applied
